import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

function shinyAvailabilityIds(events) {
  return [...new Set((events || []).flatMap((event) => {
    const legacyIds = event?.pokemonLegacy?.shinyDebuts || [];
    const detailIds = (event?.pokemon || [])
      .filter((pokemon) => pokemon?.shiny?.eventConfirmed)
      .map((pokemon) => pokemon.speciesId);
    return [...legacyIds, ...detailIds];
  }).map(Number).filter(Number.isFinite))];
}

async function readPreviousPayload(jsonPath) {
  try {
    return JSON.parse(await readFile(jsonPath, "utf8"));
  } catch {
    return {};
  }
}

export async function writeGeneratedEventData({ root, events }) {
  const dataDirectory = path.join(root, "data");
  const reportDirectory = path.join(root, "reports");
  await Promise.all([
    mkdir(dataDirectory, { recursive: true }),
    mkdir(reportDirectory, { recursive: true })
  ]);

  const jsPath = path.join(dataDirectory, "leekduck-event-data.generated.js");
  const jsonPath = path.join(dataDirectory, "leekduck-event-data.generated.json");
  const reportPath = path.join(reportDirectory, "leekduck-parser-report.json");
  const previous = await readPreviousPayload(jsonPath);
  const shinyAvailableIds = [...new Set([
    ...(previous.shinyAvailableIds || []),
    ...shinyAvailabilityIds(previous.events),
    ...shinyAvailabilityIds(events)
  ].map(Number).filter(Number.isFinite))].sort((a, b) => a - b);

  const payload = {
    generatedAt: new Date().toISOString(),
    source: "LeekDuck",
    eventCount: events.length,
    shinyAvailableIds,
    events
  };

  const js = `/* Generated by npm run refresh:events. Do not edit manually. */\nwindow.LEEKDUCK_EVENT_DATA = ${JSON.stringify(payload, null, 2)};\n`;
  await Promise.all([
    writeFile(jsPath, js, "utf8"),
    writeFile(jsonPath, JSON.stringify(payload, null, 2) + "\n", "utf8"),
    writeFile(reportPath, JSON.stringify({
      generatedAt: payload.generatedAt,
      eventCount: events.length,
      events: events.map((event) => ({
        id: event.id,
        name: event.name,
        pokemonCount: event.pokemon.length,
        shinyConfirmedCount: event.pokemon.filter((pokemon) => pokemon.shiny.eventConfirmed).length,
        methodCounts: event.pokemon.reduce((acc, pokemon) => {
          pokemon.methods.forEach((method) => { acc[method.type] = (acc[method.type] || 0) + 1; });
          return acc;
        }, {}),
        warnings: event.warnings
      }))
    }, null, 2) + "\n", "utf8")
  ]);

  return { jsPath, jsonPath, reportPath };
}
